version: "3.3"
services:
  web:
    image: nginx:1.19.10-alpine
    volumes:
      - ./build/:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/egat/ssl:ro
    ports:
      - "443:443"
      - "80:80"
    networks:
      - network_web

networks:
  web:
    name: network_web
    driver: network_web-driver-1